version: 0.2

env:
  variables:
    SOME_VAR: "cool environment variable"

phases:
  install:
    commands:
      - echo Entered the install phase...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-2)
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t node-microservice-ci-cd .
      - docker tag node-microservice-ci-cd:latest $(aws sts get-caller-identity --output text --query 'Account').dkr.ecr.us-east-2.amazonaws.com/node-microservice-ci-cd:latest      

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $(aws sts get-caller-identity --output text --query 'Account').dkr.ecr.us-east-2.amazonaws.com/node-microservice-ci-cd:latest

artifacts:
  files:
    - '**/*'