version: '2'

services:
  api:
    container_name: api
    build: .
    volumes: 
      - ./src:/usr/src/app/src
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}

  tests:
    container_name: tests
    build: 
      context: .
      dockerfile: ./tests/Dockerfile
    volumes: 
      - .:/usr/src/app/
    links:
      - api
